services:
  - type: web
    name: commentary-box-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('punkt')"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false 